### ISSUE TITLE
Minor issue: Cloudflare email protection

### ISSUE THREAD

**Issue by Julien-R44** [japa/japa.dev#1]
I just encountered a really minor problem:

![image](https://user-images.githubusercontent.com/8337858/154908886-c8fa6cd7-6b3c-47bc-b6be-588a33daae93.png)

To reproduce the problem, you must go to another page first, like this one : 

https://japa.dev/assertion-planning

Then switch to the "Dataset" page by clicking on it in the sidebar. 

As I do not use Cloudflaire I am not sure of the best solution to use, would it be to totally disable this protection?
If there is anything I can do to help, please do not hesitate.

**Comment by thetutlage** [comment]
Fixed. Thanks for reporting :)
