### ISSUE TITLE
Config-Typo @ Plugins/Assert -> Open API testing

### ISSUE THREAD

**Issue by globalexport** [japa/japa.dev#10]
### Package version

1.0.0

### Describe the bug

Config-Property would be `schemas` instead of `schema`.

File: https://github.com/japa/japa.dev/blob/develop/content/docs/plugins/assert.md#open-api-testing
Web: https://japa.dev/docs/plugins/assert#open-api-testing

**Comment by Julien-R44** [comment]
Thanks
