### ISSUE TITLE
Fix your issue template

### ISSUE THREAD

**Issue by CsnCaio** [japa/japa.dev#16]
### Package version

none

### Describe the bug

I think that Github has changed the way it creates the issues so when I click on one of the options (except this one which is Bug Report) I'm always redirected to the same page again and again.

**Comment by thetutlage** [comment]
Just tried clicking on all the links on this page and everything seems to be working fine for me.

<img width="1234" alt="Screenshot 2024-01-05 at 11 17 43 AM" src="https://github.com/japa/japa.dev/assets/1706381/d0504f0e-77c0-4631-ae02-1ef048637379">

Please right click and copy the URL and share it here for the link that is not working for you

**Comment by CsnCaio** [comment]
Course I can!
https://www.loom.com/share/72740f6b02be45799ac42b44a239d010?sid=b1cde9ec-0288-4e53-ba97-f43b29b2f2da
