### ISSUE TITLE
Typescript docs are incorrect

### ISSUE THREAD

**Issue by OmgImAlexis** [japa/japa.dev#4]
Since you locked https://github.com/japa/runner/issues/3 I guess I have to open another issue here since the docs for typescript don't mention anything at all about mocking which is one of the main things people use when testing.

Using `esno` doesn't work with tests that are written in typescript `esmo` doesn't work since it doesn't allow mocking as it uses ES modules under the hood that can't be modified without a loader.

All of this should be mentioned in the docs.

**Comment by thetutlage** [comment]
Mocking has nothing to do with TypeScript. Mocking is a general concept. 

Second I cannot put the issues of other tools in the documentation. You simply need to read their guides, if you find it limiting, then report it to the correct package.

I locked the issue, coz there is nothing I can do about it. `esno` and `esmo` are both the tools targeted towards TypeScript. Atleast, this is what I read in their README. https://github.com/antfu/esno

**Comment by OmgImAlexis** [comment]
>  You simply need to read their guides, if you find it limiting, then report it to the correct package.

What's the harm in mentioning the limition in the docs? Users are going to attempt to use this and find they're in the same boat I'm in and they can't even reply to the issue since you locked it. That helps no one at all. 

> You simply need to read their guides

I can't "simply" do anything as there are no guides on how to fix this issue. Hence the issue being opened here. 

> esno and esmo are both the tools targeted towards TypeScript. Atleast, this is what I read in their README. [antfu/esno](https://github.com/antfu/esno)

So your answer is "it's someone elses fault" got it... 🙃

**Comment by thetutlage** [comment]
Sorry, I have no interests in catering to trolls :)
