### ISSUE TITLE
Inconsistency between docs and source code for interpolating datasets

### ISSUE THREAD

**Issue by ndianabasi** [japa/japa.dev#6]
I discovered an inconsistency b/w the docs and source for interpolating indexes for datasets.

The docs says we can use `$index` which isn't working. However, the source code uses: `$i` which works: https://github.com/japa/core/blob/77363c04dd2012f1751696f1184e1a869017ad52/src/Interpolate/index.ts#L44-L47

I don't want to send a PR until I'm sure of which of these variables (`$i` or `$index`) is meant to be used in the source code or docs.

Also, I could not find a way of interpolating the values from string arrays such as `['undefined', 'null', 'foo', 'bar']` in the test titles.

Packages:

```json
{
    "@adonisjs/core": "^5.8.3",
    "@japa/api-client": "^1.4.0",
    "@japa/assert": "^1.3.4",
    "@japa/preset-adonis": "^1.1.0",
    "@japa/run-failed-tests": "^1.0.7",
    "@japa/runner": "^2.0.9",
    "@japa/spec-reporter": "^1.1.12",
}
```

**Comment by thetutlage** [comment]
Docs should be fixed here. It should be `$i`

**Comment by ndianabasi** [comment]
Great.

What about this:

> Also, I could not find a way of interpolating the values from string arrays such as ['undefined', 'null', 'foo', 'bar'] in the test titles.

I can write the docs for it at once.

**Comment by thetutlage** [comment]
> Also, I could not find a way of interpolating the values from string arrays such as ['undefined', 'null', 'foo', 'bar'] in the test titles.

I see that there is no way to reference the literal values from an array. Have to think of the best way to do it and then implement it

**Comment by ndianabasi** [comment]
> I see that there is no way to reference the literal values from an array. Have to think of the best way to do it and then implement it

Okay. This can be a separate issue. 

This PR should close this issue: https://github.com/japa/japa.dev/pull/7

Thank you.

**Comment by thetutlage** [comment]
Closed by https://github.com/japa/japa.dev/pull/7
